name: int_nmt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.10.14=0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1h=h7b6447c_0
  - python=3.6.12=hcff3b4d_2
  - readline=8.0=h7b6447c_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.11.0
    - antlr4-python3-runtime==4.8
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bitarray==2.3.4
    - bleach==3.2.1
    - blis==0.7.4
    - cachetools==4.2.1
    - captum==0.4.0
    - catalogue==2.0.3
    - certifi==2020.11.8
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - configparser==5.0.2
    - contextvars==2.4
    - cycler==0.10.0
    - cymem==2.0.5
    - cython==0.29.21
    - dataclasses==0.8
    - datasets==1.2.1
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.3
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - editdistance==0.5.3
    - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl
    - entrypoints==0.3
    - filelock==3.0.12
    - flatbuffers==1.12
    - ftfy==5.9
    - future==0.18.2
    - gast==0.2.2
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.25.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - hydra-core==1.0.7
    - idna==2.10
    - immutables==0.15
    - importlib-metadata==2.0.0
    - importlib-resources==3.3.0
    - ipykernel==5.3.4
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.2
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==0.17.0
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.7.0
    - jupyterlab==2.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==1.2.0
    - jupyterlab-widgets==1.0.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - llvmlite==0.35.0
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mistune==0.8.4
    - mosestokenizer==1.1.0
    - multiprocess==0.70.11.1
    - murmurhash==1.0.5
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - networkx==2.5
    - nltk==3.5
    - nodejs==0.1.1
    - notebook==6.1.5
    - npm==0.1.1
    - numba==0.52.0
    - numpy==1.19.4
    - oauthlib==3.1.0
    - omegaconf==2.0.5
    - opencv-python==4.5.4.60
    - openfile==0.0.7
    - opt-einsum==3.3.0
    - optional-django==0.1.0
    - packaging==20.4
    - pandas==1.1.4
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pathtools==0.1.2
    - pathy==0.4.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - pip==21.0.1
    - pip-tools==5.3.1
    - plotly==4.14.3
    - portalocker==2.0.0
    - preshed==3.0.5
    - prometheus-client==0.9.0
    - promise==2.3
    - prompt-toolkit==3.0.8
    - protobuf==3.14.0
    - psutil==5.8.0
    - ptyprocess==0.6.0
    - pyarrow==2.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pydantic==1.7.3
    - pygments==2.7.2
    - pynndescent==0.5.2
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pyyaml==5.3.1
    - pyzmq==20.0.0
    - regex==2020.11.13
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.7
    - sacrebleu==1.4.14
    - sacremoses==0.0.43
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - seaborn==0.11.0
    - send2trash==1.5.0
    - sentence-transformers==0.4.1.2
    - sentencepiece==0.1.6
    - sentry-sdk==1.4.3
    - setuptools==56.0.0
    - shortuuid==1.0.1
    - six==1.15.0
    - sklearn==0.0
    - smart-open==3.0.0
    - smmap==4.0.0
    - spacy==3.0.5
    - spacy-alignments==0.8.3
    - spacy-legacy==3.0.2
    - spacy-transformers==1.0.1
    - srsly==2.4.1
    - subprocess32==3.5.4
    - subword-nmt==0.3.7
    - tensorboard==1.9.0
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - tensorflow-estimator==2.0.1
    - termcolor==1.1.0
    - terminado==0.9.1
    - testpath==0.4.4
    - thinc==8.0.3
    - threadpoolctl==2.1.0
    - tokenizers==0.9.4
    - toolwrapper==2.1.0
    - torch==1.7.1
    - torchaudio==0.7.2
    - torchcontrib==0.0.2
    - torchvision==0.8.2
    - tornado==6.1
    - tqdm==4.49.0
    - traitlets==4.3.3
    - transformers==4.2.2
    - typer==0.3.2
    - typing-extensions==3.7.4.3
    - uctools==1.3.0
    - umap-learn==0.5.1
    - urllib3==1.26.2
    - wandb==0.12.4
    - wasabi==0.8.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wheel==0.36.2
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xxhash==2.0.0
    - yaspin==2.1.0
    - zipp==3.4.0
prefix: /home/usuaris/veu/gerard.ion.gallego/conda/envs/int_nmt

